#!/bin/bash
set -e

# update desktop database and icon cache
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database >/dev/null || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -t -f /usr/share/icons/hicolor >/dev/null || true
fi

exit 0
